# Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
# See: https://circleci.com/docs/configuration-reference/#executor-job
docker:
  - image: mcr.microsoft.com/dotnet/sdk:7.0.402@sha256:d0755fbf1ed34aecd79c127fd1dd01b80587acdb8ff50e5a68d1adf8b076922b
# Add steps to the job
# See: https://circleci.com/docs/configuration-reference/#steps
steps:
  - checkout
  - setup_remote_docker:
      version: 20.10.14
  - run:
      name: Run tests
      command: dotnet test