version: 2.1

orbs:
  win: circleci/windows@5.0


jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - run: 
          command: |
            mkdir workspace
            echo "Hello world!" > workspace/helloworld.txt
      - persist_to_workspace:
          paths: 
            - workspace
  windows-workspace:
    executor:
      name: win/server-2022
      version: current
    steps:
      - attach_workspace:
          at: workspace
      - run: type workspace\helloworld.txt

workflows:
  build:
    jobs:
      - say-hello
      - windows-workspace:
          requires:
            - say-hello

  only-on-branches-with-foo:
    when:
      or:
        - matches: { pattern: "foo/.*", value: << pipeline.git.branch >>}
    jobs:
      - say-hello