version: 2.1

jobs:
  postgres-tests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0.402@sha256:d0755fbf1ed34aecd79c127fd1dd01b80587acdb8ff50e5a68d1adf8b076922b
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Run tests
          command: dotnet test
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "hello world!"

workflows:
  build:
    jobs:
      - postgres-tests
  only-on-branches-with-foo:
    when:
      or:
        - matches: { pattern: "foo/.*", value: << pipeline.git.branch >>}
    jobs:
      - say-hello