version: 2.1

orbs:
  win: circleci/windows@5.0


jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - run: 
          name: Create large file
          command: |
            mkdir workspace
            dd if=/dev/random of=workspace/big.file bs=1048576 count=500
      - persist_to_workspace:
          root: workspace
          paths: 
            - ./
  windows-workspace:
    executor:
      name: win/server-2022
      version: current
    steps:
      - attach_workspace:
          at: workspace
      - run: 
          name: List files
          command: |
            dir workspace

workflows:
  build:
    jobs:
      - say-hello
      - windows-workspace:
          requires:
            - say-hello

  only-on-branches-with-foo:
    when:
      or:
        - matches: { pattern: "foo/.*", value: << pipeline.git.branch >>}
    jobs:
      - say-hello